### Q1. You have IRIS data set, and you have 3 target value (0, 1, 2). You need to drop value 2.

In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()

In [ ]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
df1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

"""
here np.c_ is actually concatening the values
Translates slice objects to concatenation along the second axis. 
Example
np.c_[np.array([1,2,3]), np.array([4,5,6])]
array([[1, 4],
       [2, 5],
       [3, 6]])

"""

In [ ]:
df1.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [ ]:
df1['target'].unique()

array([0., 1., 2.])

In [ ]:
#df2 = df1['target'].isin[0, 1]

df2=df1[df1['target'].isin(['0','1'])]

In [ ]:
df2['target'].unique()

array([0., 1.])

### Q2. Calculate the step size and slope
<img src="https://github.com/rnomadic/ML_Learning/blob/main/MyPythonCode/EY-Challenge.PNG?raw=1">

### Q3. How grid search works? 
GridSearchCV is a library function that is a member of sklearn’s model_selection package. It helps to loop through predefined hyperparameters and fit your estimator (model) on your training set. So, in the end, you can select the best parameters from the listed hyperparameters.




In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
params = {
    'n_neighbors' : [5, 25],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
}
grid_kn = GridSearchCV(estimator = kn,
                        param_grid = params,
                        scoring = 'accuracy', 
                        cv = 5, 
                        verbose = 1,
                        n_jobs = -1)
grid_kn.fit(X_train, y_train)

# Q4 How you do parameter tuning in RF
https://towardsdatascience.com/random-forest-hyperparameters-and-how-to-fine-tune-them-17aee785ee0d

Hyper-parameter considerations, tips and tricks
The most important hyper-parameters of a Random Forest that can be tuned are:

The Nº of Decision Trees in the forest (in Scikit-learn this parameter is called n_estimators)

The criteria with which to split on each node (Gini or Entropy for a classification task, or the MSE or MAE for regression)

The maximum depth of the individual trees. The larger an individual tree, the more chance it has of overfitting the training data, however, as in Random Forests we have many individual trees, this is not such a big problem.

The minimum samples to split on at an internal node of the trees. Playing with this parameter and the previous one we could regularise the individual trees if needed.

Maximum number of leaf nodes. In Random Forest this is not so important, but in an individual Decision Tree it can greatly help reduce over-fitting as well and also help increase the explainability of the tree by reducing the possible number of paths to leaf nodes. Learn how to use Decision Trees to build explainable ML models here.

Number of random features to include at each node for splitting.

The size of the bootstrapped dataset to train each Decision Tree with.


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
> RandomForestClassifier(bootstrap=True, class_weight=None, criterion=’gini’,
 max_depth=None, max_features=’auto’, max_leaf_nodes=None,
 min_impurity_split=1e-07, min_samples_leaf=1,
 min_samples_split=2, min_weight_fraction_leaf=0.0,
 n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
 verbose=0, warm_start=False)

y_pred = rf.predict(x_test)

https://medium.com/all-things-ai/in-depth-parameter-tuning-for-random-forest-d67bb7e920d

### Q4. Suppose you have colinearity between variable A and varible B. Which variable you will drop A or B?

### Q5. What do you understand by optimization? How it works?
https://towardsdatascience.com/demystifying-optimizations-for-machine-learning-c6c6405d3eea
https://serokell.io/blog/ml-optimization
https://machinelearningmastery.com/tour-of-optimization-algorithms/#:~:text=Optimization%20is%20the%20problem%20of,to%20training%20artificial%20neural%20networks.


Machine learning optimization is the process of adjusting hyperparameters in order to minimize the cost function by using one of the optimization techniques. It is important to minimize the cost function because it describes the discrepancy between the true value of the estimated parameter and what the model has predicted.

**First-Order Algorithms**
First-order optimization algorithms explicitly involve using the first derivative (gradient) to choose the direction to move in the search space.

The procedures involve first calculating the gradient of the function, then following the gradient in the opposite direction (e.g. downhill to the minimum for minimization problems) using a step size (also called the learning rate).

First-order algorithms are generally referred to as gradient descent, with more specific names referring to minor extensions to the procedure, e.g.:

    Gradient Descent
    Momentum
    Adagrad
    RMSProp
    Adam

**Gradient Descent**

**Stochastic Gradient Descent**
Stochastic gradient descent (SGD) is the simplest optimization algorithm used to find parameters which minimizes the given cost function. Apparently, for gradient descent to converge to optimal minimum, cost function should be convex. 

**Adaptive Learning Rate Method**
    
    AdaDelta, RMSProp, Adam use the exponential averaging to provide effective updates.

    Adagrad: weights with a high gradient will have low learning rate and vice versa
    RMSprop: adjusts the Adagrad method such that it reduces its monotonically decreasing learning rate. 
    Adam is almost similar to RMSProp but with momentum
    

**Population Algorithms**
Population optimization algorithms are stochastic optimization algorithms that maintain a pool (a population) of candidate solutions that together are used to sample, explore, and hone in on an optima.

Examples of population optimization algorithms include:

    Genetic Algorithm
    
   <img src = 'Genetic_Algorithm.jpg'>