Numpy is the core library for scientific computing in Python.
It provides a high-performance multidimensional array object, and tools for working with these arrays.
Case 1 : Array basic

In [1]:
import numpy as np
b = np.array([[1,2,3], [4,5,6]])
print(b.shape) # It will show 2 row 3 col

(2, 3)


In [2]:
print(b[0,0], b[1, 2]) # print first row 1st col, 2nd row 3rd col (0 indexed)

1 6


In [6]:
v = np.array([1,2,3,4])
x = v[1:-1] # take everything except 1st and last
print (x)

[2 3]


In [19]:
# Instead of using Rank 1 array use Matrix
a = np.random.randn(5)
print(a)

print()

a = np.random.randn(5, 1)
print(a)
print()
print(a.T)
print()
print(np.dot(a, a.T))

print(a.shape)

assert(a.shape==(1,5))
a = a.reshape(5, 1)

[-0.49612439  1.63924489 -0.0418718   0.9705838  -0.62209765]

[[-0.71897423]
 [ 1.21462944]
 [ 0.79881788]
 [-0.60675426]
 [-0.50744882]]

[[-0.71897423  1.21462944  0.79881788 -0.60675426 -0.50744882]]

[[ 0.51692394 -0.87328727 -0.57432947  0.43624068  0.36484262]
 [-0.87328727  1.47532468  0.97026772 -0.73698159 -0.61636228]
 [-0.57432947  0.97026772  0.63811001 -0.48468616 -0.40535919]
 [ 0.43624068 -0.73698159 -0.48468616  0.36815074  0.30789673]
 [ 0.36484262 -0.61636228 -0.40535919  0.30789673  0.2575043 ]]
(5, 1)


AssertionError: 

# Tensors

Tensors are just like vectors and matrices, but they can have more dimensions. For example, to create a 3x3x2x1 tensor, you could do the following:

In [3]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[18]]]])

t.shape

(3, 3, 2, 1)

In [4]:
t[2][1][1][0] 

16

# Element-wise operations

In [8]:
values = [1, 2, 3, 4, 5]
values = np.array(values) + 5

values


array([ 6,  7,  8,  9, 10])

# Matrix Multiplication

## Important Reminders About Matrix Multiplication
. The number of columns in the left matrix must equal the number of rows in the right matrix. <br>
. The answer matrix always has the same number of rows as the left matrix and the same number of columns as the right matrix. <br>
. Order matters. Multiplying A•B is not the same as multiplying B•A. <br>
. Data in the left matrix should be arranged as rows., while data in the right matrix should be arranged as columns. <br>


In [16]:
m = np.array([[1, 2, 3], [4, 5, 6]])
n = m * m # square of matrix
n

array([[ 1,  4,  9],
       [16, 25, 36]])

In [19]:
p = np.multiply(m, n)
p

array([[  1,   8,  27],
       [ 64, 125, 216]])

## Matrix Product
To find the matrix product, you use NumPy's matmul function.<br>

If you have compatible shapes, then it's as simple as this:

In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a.shape)
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(b.shape)
c = np.matmul(a, b)
print(c.shape)
c

(2, 4)
(4, 3)
(2, 3)


array([[ 70,  80,  90],
       [158, 184, 210]])

In [24]:
# If the size is not compatible, it will throw the error
# Remember (row1 x col1) can be multiplied by (col1 x col2)
c = np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

## Numpy dot function
While these functions return the same results for two dimensional data, you should be careful about which you choose when working with other data shapes. You can read more about the differences, and find links to other NumPy functions, in the [matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) and [dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) documentation.

In [25]:
a = np.array([[1, 2], [3, 4]])
b = np.dot(a, a)
c = np.matmul(a, a)

print(b)
print(c)

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


## Matrix Transpose

You can safely use a transpose in a matrix multiplication if the data in both of your original metrices is arranged as rows. For example 3X2 matrix can be multiplied with 4X2 by transposing 4X2 matrix to 2X4 if the data is arranged in rows for both.


In [31]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m)
m_t = m.T
print("\ntransposed version\n")
print(m_t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

transposed version

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


<font color = 'red' > Matrix and Matrix transpose both refering to the same data </font>. Numpy has just changed the indexing.
So any change in Matrix transpose will affect original Matrix as well.

In [33]:
m_t[3][1] = 200
print(m_t)
print("\noriginal version\n")
print(m) # You changed m_t but it actually affects m also

[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]

original version

[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


## Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes <br>
when performing arithmetic operations. Frequently we have a smaller array and a larger array <br>
and we want to use the smaller array multiple times to perform some operation on the larger array <br>




In [16]:
"Case 1 : Using Loop, inefficient if the array is very big size, looping will be huge"
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13,14, 15]])
print(x.shape)
v= np.array([1, 0, 1])
print(v.shape)
y = np.empty_like(x) #take a empty matrix like x
 
for i in range (5):
    y[i, : ] = x[i, : ] + v

print(y)

print()
w=np.array([[1], [1], [1], [1], [1]])
print(w)
print(w.shape)
z = np.empty_like(x)
for i in range (3):
    z[:, i] = x[:, i] + w

print(z)

(5, 3)
(3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]
 [14 14 16]]

[[1]
 [1]
 [1]
 [1]
 [1]]
(5, 1)


ValueError: could not broadcast input array from shape (5,5) into shape (5)

In [9]:
# Case 2
import numpy as np
x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9], 
              [10, 11, 12], 
              [13,14, 15]])

sum_col = x.sum(axis=0) # we want to add in col wise
print(sum_col)

percentage = 100*x / sum_col
print()
print(percentage)

sum_row = x.sum(axis=1) # we want to add in row wise
print()
print(sum_row)


[35 40 45]

[[  2.85714286   5.           6.66666667]
 [ 11.42857143  12.5         13.33333333]
 [ 20.          20.          20.        ]
 [ 28.57142857  27.5         26.66666667]
 [ 37.14285714  35.          33.33333333]]

[ 6 15 24 33 42]


### newaxis

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

In [9]:
# 1D array
arr = np.arange(4)
print(arr.shape)
print(arr)

(4,)
[0 1 2 3]


In [8]:
# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis, :]
print(row_vec.shape)
print(row_vec)

(1, 4)
[[0 1 2 3]]


In [13]:
# make it as column vector by inserting an axis along second dimension
col_vec = arr[:, np.newaxis]
print(col_vec.shape)
print(col_vec)

(4, 1)
[[0]
 [1]
 [2]
 [3]]


In [18]:
from sklearn import datasets, linear_model


# Load the diabetes dataset
diabetes = datasets.load_diabetes()

print(diabetes.data.shape)

# Use only one feature
# use np.newaxis to increase the dimension of array so that NumPy can broadcast.
diabetes_X = diabetes.data[:, np.newaxis, 2] 

print(diabetes_X.shape)



(442, 10)
(442, 1)


In [27]:
# Split the data into training/testing sets
diabetes_X_train = diabetes_X[:-20] # start to just before last 20
diabetes_X_test = diabetes_X[-20:]  # just before last 20 to last

print(diabetes_X_train.shape)
print(diabetes_X_test.shape)

(422, 1)
(20, 1)


### numpy.argsort(a, axis=-1, kind='quicksort', order=None)
### Returns the indices that would sort an array.



Parameters:	
a : array_like

Array to sort.

axis : int or None, optional

Axis along which to sort. The default is -1 (the last axis). If None, the flattened array is used.

kind : {‘quicksort’, ‘mergesort’, ‘heapsort’}, optional

Sorting algorithm.

order : str or list of str, optional

When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

Returns:	
index_array : ndarray, int

Array of indices that sort a along the specified axis. If a is one-dimensional, a[index_array] yields a sorted a.

In [25]:
# Sorting numpy array 

ele = np.array([20, 1, 7, 4, 9, 15])

ids = np.array(ele).argsort()
print("original numpy array:", ele)
print("sorted numpy array (ascending order):  ", ele[ids])

ids = np.array(ele).argsort()[::-1]
print("sorted numpy array (Decending order):  ", ele[ids])

original numpy array: [20  1  7  4  9 15]
sorted numpy array (ascending order):   [ 1  4  7  9 15 20]
sorted numpy array (Decending order):   [20 15  9  7  4  1]


In [23]:
# Two-dimensional array:

x = np.array([[0, 3], [2, 2]])
print("original array: ")
print( x)
print("sorts along first axis (down): ")
print(np.argsort(x, axis=0)) # sorts along first axis (down)
print("sorts along last axis (across): ")
print(np.argsort(x, axis=1))  # sorts along last axis (across)


original array: 
[[0 3]
 [2 2]]
sorts along first axis (down): 
[[0 1]
 [1 0]]
sorts along last axis (across): 
[[0 1]
 [0 1]]


In [48]:
import numpy as np

def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    
    min = np.amin(input_array)
   
    inputs_minus_min = input_array - min

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    max = np.amax(input_array)
    inputs_div_max = input_array / max

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if len(m1[0])!= len(m2) and len(m2[0])!= len(m1) :
        return False
    


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if len(m1[0])== len(m2):
        return np.matmul(m1, m2)
    else:
        return np.matmul(m2, m1)
    
def find_mean(values):
    sum=0
    for i in range(len(values)):
        sum +=values[i]
    return sum/len(values)

input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))


print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[-0.14285714  0.28571429  1.        ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
